#+TITLE: Emacs Config
#+STARTUP: overview
#+PROPERTY: header-args :tangle init.el

* Preface
This literate config is set to  dump all source block into into ~init.el~

This means changes from here do not get automatically get loaded on rerunning Emacs!

To reload config you can:

1. use ~C-c C-v t~ to update ~init.el~ and restart
2. use ~C-x C-e~ on a lisp expression to run it on the fly
3. use ~C-c r~ to run ~dnl/reload-init-file~ to tangle and reload everything in one go

To exclude an SRC block from tangling use ~#+begin_src emacs-lisp :tangle no~

** Load org config via init.el

Always tangles ~emacs.org~ file on startup. Tangling from ~dnl/reload-init-file~ can be removed if used

#+begin_src emacs-lisp :tangle no
;;
;; barebone init.el, load config in literate orgmode file
;;

;; load emacs config in orgmode file
(require 'org)
(org-babel-load-file "~/.emacs.d/emacs.org")

;; alt/new way of loading
;;(org-babel-load-file
;; (expand-file-name
;;  "emacs.org"
;;  user-emacs-directory))
#+end_src

* Cheatsheet
Cheatsheet for basic emacs commands and commands of packages
** basic commands
*** navigating text

| C-a   | Move to beginning of line                          |
| M-m   | Move to first non-whitespace character on the line |
| C-e   | Move to end of line                                |
| C-f   | Move forward one character                         |
| C-b   | Move backward one character                        |
| M-f   | Move forward one word (I use this a lot)           |
| M-b   | Move backward one word (I use this a lot, too)     |
| C-s   | Regex search for text in current buffer            |
| C-r   | Same as C-s, but search in reverse                 |
| M-<   | Move to beginning of buffer                        |
| M->   | Move to end of buffer                              |
| M-g g | Go to line                                         |

*** manipulating text

| C-SPC | select region                         |
| C-w   | Kill region                           |
| M-w   | Copy region to kill ring              |
| C-y   | Yank                                  |
| M-y   | Cycle through kill ring after yanking |
| M-d   | Kill word                             |
| C-k   | Kill line                             |

*** navigate windows,

| C-x o | Switch cursor to another window                                        |
| C-x 1 | Delete all other windows, leaving only the current window in the frame |
| C-x 2 | Split frame above and below                                            |
| C-x 3 | Split frame side by side                                               |
| C-x 0 | Delete current window                                                  |

** org mode

[[http://ehneilsen.net/notebook/orgExamples/org-examples.html][comprehensive overview]]
[[http://orgmode.org/orgcard.txt][reference card]]
    
| TAB     | toggle subtree |
| C-c C-l | enter links    |
| C-c C-e | export file    |

** magit basics

| C-x g | open magit status                                                        |
| S     | stages all files                                                         |
| c c   | initiates a commit. Write the message and press C-c C-c to create commit |
| P u   | pushes to the upstream branch                                            |

* Custom Variables

Setup misc variables to use later.
'Per System' variables are loaded via an ~dnl-custom-vars.el~, if this does not exist use fallback values

#+BEGIN_SRC emacs-lisp

;; use dnl prefixed file, 
(setq custom-file "~/.config/emacs/dnl-custom-vars.el")

(cond ((file-exists-p custom-file)
        ;; if custom file exists load it and its values
        (load custom-file))
       (t
        ;; if not use standard values
        ;; cons: this means these need to be tracked in two places
        (defvar dnl/default-font-size 130)
        (defvar dnl/org-agenda-path "~/Sync/org/")
        ))
 

 (defvar dnl/emacs-conf-path "~/.config/emacs/")
 (defvar dnl/emacs-conf-org-path "~/.config/emacs/emacs.org")
 (defvar dnl/emacs-conf-init-path "~/.config/.emacs/init.el")
;; Try Fira for Larger Screen slowness
;; else try: https://www.reddit.com/r/emacs/comments/zgp6kw/gui_emacs_weird_the_bigger_the_frame_size_is_the/
;; (defvar dnl/default-font "Iosevka SS08")
 (defvar dnl/default-font "Fira Code")
 (defvar dnl/indent-width 2)

#+END_SRC

* Package Management
#+BEGIN_SRC emacs-lisp
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
			                   ("org" . "https://orgmode.org/elpa/")
			                   ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

;; Initialize use-package on non-Linux platforms
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
;; always download packages if they don't already exist
(setq use-package-always-ensure t)
#+END_SRC

* Keyboard Bindings

General rebindings

#+BEGIN_SRC emacs-lisp
;; Make ESC quit prompts
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

;; Jump to emacs config
(global-set-key (kbd "C-c e") '(lambda ()
			                           (interactive)
			                           (find-file dnl/emacs-conf-org-path)))

;; Reload Emacs Config
(defun dnl/reload-init-file ()
  (interactive)
  ;; export config to init.el
  (org-babel-tangle-file dnl/emacs-conf-org-path dnl/emacs-conf-init-path)
  ;; reload init file
  (load-file user-init-file)
  ;; restart org mode, else there are some hook issues. Disabled as also annoying if not changing stuff for org, run manually if needed
  ;;(org-mode-restart)
  )

(global-set-key (kbd "C-c r") 'dnl/reload-init-file) 

;; Show buffer menu
(global-set-key (kbd "C-x C-b") 'buffer-menu)

;; Kill line backward
;; alternative: https://github.com/purcell/emacs.d/blob/485a3af948db4671baf73f14bced123bae3112f3/init-editing-utils.el#L147
(global-set-key (kbd "C-<backspace>") (lambda ()
                                        (interactive)
                                        (kill-line 0)
                                        (indent-according-to-mode)))
#+END_SRC

** god mode
<menu> is bound to caps lock in os settings. <menu> normally opens the m-x buffer, would be sweet to have as an actual key. what to replace the god-mode trigger with?
<escape> already is uded as an alternative for C-g to quit menus.

#+begin_src emacs-lisp
(use-package god-mode
  :bind (("<menu>" . god-local-mode)))
#+end_src

** which-key

Show possible kyebindings after short delay

#+begin_src emacs-lisp
(use-package which-key
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay 1))
#+end_src

* General Config
** UI
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)

(scroll-bar-mode -1)        ;; Disable visible scrollbar
(tool-bar-mode -1)          ;; Disable the toolbar
;; (menu-bar-mode -1)          ; Disable the menu bar
(tooltip-mode -1)           ;; Disable tooltips
(set-fringe-mode 10)        ;; Give some breathing room
(setq ring-bell-function 'ignore) ;; no audio bell
(blink-cursor-mode 0)       ;; no blinking cursor

;; enable right click context menu
(context-menu-mode t)

;; show line and column numbers globaly
(column-number-mode)
(global-display-line-numbers-mode t)

;; but don't show line numbers in certain modes
(dolist (mode '(org-mode-hook
	              term-mode-hook
	              eshell-mode-hook
                vterm-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))

;; transform yes-or-no questions into y-or-n
(defalias 'yes-or-no-p 'y-or-n-p)

;; use olivetti mode for writing
(use-package olivetti
  :init
  (setq olivetti-body-width 80)
  (setq olivetti-style 'fancy))
#+END_SRC

** Theme

#+BEGIN_SRC emacs-lisp :tangle no~
 (use-package spacemacs-theme
  :init
  (load-theme 'spacemacs-dark t))
#+END_SRC

#+begin_src emacs-lisp
(use-package mindre-theme
  :vc (:url "https://github.com/erikbackman/mindre-theme" :rev :newest)
  :custom
  (mindre-use-more-bold t)
  :config
  (load-theme 'mindre t))
#+end_src

Icons similiar to all-the-icons, e.g used by doom-modeline

#+begin_src emacs-lisp
(use-package nerd-icons
  ;; :custom
  ;; The Nerd Font you want to use in GUI
  ;; "Symbols Nerd Font Mono" is the default and is recommended
  ;; but you can use any other Nerd Font if you want
  ;; (nerd-icons-font-family "Symbols Nerd Font Mono")
  )
#+end_src

Load custom theme from the themes folder (WIP)
update with mindre as basis but keep color choices + larger and bold org headings
#+begin_src emacs-lisp :tangle no~
(add-to-list 'custom-theme-load-path "~/.config/emacs/themes/")
(load-theme 'calcite t)
#+end_src

** Font

#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default nil :font dnl/default-font :height dnl/default-font-size)

;; Set the fixed pitch face
(set-face-attribute 'fixed-pitch nil :font dnl/default-font :height  dnl/default-font-size)

#+END_SRC

Use emojis everywhere

;;#+begin_src emacs-lisp
;;(use-package emojify
;;  :hook (after-init . global-emojify-mode))
;;#+end_src
   
** Modeline

#+BEGIN_SRC emacs-lisp
(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 15)))
#+END_SRC

** Saving and Backup

All backup files get sent to ~/.config/emacs/backups/~ to not clutter the file system

#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist '(("." . "~/.config/emacs/backups/")))
(setq delete-old-versions -1)
(setq version-control t)
(setq vc-make-backup-files t)
(setq auto-save-file-name-transforms '((".*" "~/.config/emacs/auto-save-list/" t)))
#+END_SRC

** Completion

Use Ivy + Counsel for more convenient completion systems. Basically replace emacs own completion

Currently disabled to test out vertico, consult, embark, orderless, see below

#+BEGIN_SRC emacs-lisp
(use-package ivy
  :disabled
  :diminish
  :bind (("C-s" . swiper)
	       :map ivy-minibuffer-map
	       ("TAB" . ivy-alt-done)	
	       ("C-l" . ivy-alt-done)
	       ("C-j" . ivy-next-line)
	       ("C-k" . ivy-previous-line)
	       :map ivy-switch-buffer-map
	       ("C-k" . ivy-previous-line)
	       ("C-l" . ivy-done)
	       ("C-d" . ivy-switch-buffer-kill)
	       :map ivy-reverse-i-search-map
	       ("C-k" . ivy-previous-line)
	       ("C-d" . ivy-reverse-i-search-kill))
  :config
  (ivy-mode 1))

(use-package counsel
  :disabled
  :bind (
	       ("C-x C-f" . counsel-find-file)
	       ("C-x b" . counsel-ibuffer)
	       ;; ("M-y" . counsel-yank-pop)
	       ("M-x " . counsel-M-x))
  :config
  (counsel-mode 1))
#+END_SRC

#+BEGIN_SRC emacs-lisp
;; Completion systems based on the standard Emacs completing-read API
(use-package consult
  ;; Replace bindings. Lazily loaded due by `use-package'.
  :bind (;; C-c bindings (mode-specific-map)
         ("C-c h" . consult-history)
         ("C-c m" . consult-mode-command)
         ("C-c k" . consult-kmacro)
         ;; C-x bindings (ctl-x-map)
         ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
         ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
         ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
         ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
         ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
         ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
         ;; Custom M-# bindings for fast register access
         ("M-#" . consult-register-load)
         ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
         ("C-M-#" . consult-register)
         ;; Other custom bindings
         ("M-y" . consult-yank-pop)                ;; orig. yank-pop
         ("<help> a" . consult-apropos)            ;; orig. apropos-command
         ;; M-g bindings (goto-map)
         ("M-g e" . consult-compile-error)
         ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
         ("M-g g" . consult-goto-line)             ;; orig. goto-line
         ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
         ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
         ("M-g m" . consult-mark)
         ("M-g k" . consult-global-mark)
         ("M-g i" . consult-imenu)
         ("M-g I" . consult-imenu-multi)
         ;; M-s bindings (search-map)
         ("M-s d" . consult-find)
         ("M-s D" . consult-locate)
         ("M-s g" . consult-grep)
         ("M-s G" . consult-git-grep)
         ("M-s r" . consult-ripgrep)
         ("C-s" . consult-line)
         ;; ("M-s l" . consult-line)
         ("M-s L" . consult-line-multi)
         ("M-s m" . consult-multi-occur)
         ("M-s k" . consult-keep-lines)
         ("M-s u" . consult-focus-lines)
         ;; Isearch integration
         ("M-s e" . consult-isearch-history)
         :map isearch-mode-map
         ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
         ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
         ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
         ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
         ;; Minibuffer history
         :map minibuffer-local-map
         ("M-s" . consult-history)                 ;; orig. next-matching-history-element
         ("M-r" . consult-history))                ;; orig. previous-matching-history-element

  ;; Enable automatic preview at point in the *Completions* buffer. This is
  ;; relevant when you use the default completion UI.
  :hook (completion-list-mode . consult-preview-at-point-mode))


;; completion style that divides the pattern into space-separated components, and matches candidates that match all of the components in any order
;; e.g.: searching "region indent" will match with "indent-region"
(use-package orderless
  :init
  (setq completion-styles '(orderless)
        completion-category-defaults nil
        completion-category-overrides '((file (styles partial-completion)))))

;; Vertical completion UI based on the default completion system
(use-package vertico
  :init
  (vertico-mode)

  ;; Different scroll margin
  ;; (setq vertico-scroll-margin 0)

  ;; Show more candidates
  ;; (setq vertico-count 20)

  ;; Grow and shrink the Vertico minibuffer
  (setq vertico-resize t)

  ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
  ;; (setq vertico-cycle t)
  )

;; Persist history over Emacs restarts. Vertico sorts by history position.
(use-package savehist
  :init
  (savehist-mode))

;; Enable richer annotations using the Marginalia package
(use-package marginalia
  ;; Either bind `marginalia-cycle` globally or only in the minibuffer
  :bind (("M-A" . marginalia-cycle)
         :map minibuffer-local-map
         ("M-A" . marginalia-cycle))

  ;; The :init configuration is always executed (Not lazy!)
  :init
  ;; Must be in the :init section of use-package such that the mode gets
  ;; enabled right away. Note that this forces loading the package.
  (marginalia-mode))

;; Sort of right-click contextual menu for Emacs, accessed through the embark-act command (which you should bind to a convenient key), offering you relevant actions to use on a target determined by the context
(use-package embark
  :bind
  (("C-." . embark-act)         ;; C-. by default but does not work on gnome, run ~gsettings set org.freedesktop.ibus.panel.emoji hotkey "[]"~ to get it back
   ("C-;" . embark-dwim)        ;; good alternative: M-.
   ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'

  :init
  ;; Optionally replace the key help with a completing-read interface
  (setq prefix-help-command #'embark-prefix-help-command)

  :config
  ;; Hide the mode line of the Embark live/completions buffers
  (add-to-list 'display-buffer-alist
               '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))

;; Consult users will also want the embark-consult package.
(use-package embark-consult
  :after (embark consult)
  :demand t ; only necessary if you have the hook below
  ;; if you want to have consult previews as you move around an
  ;; auto-updating embark collect buffer
  :hook
  (embark-collect-mode . consult-preview-at-point-mode))
#+END_SRC


use corfu for completion at point

#+begin_src emacs-lisp
(use-package corfu
  :custom
  (corfu-auto t)
  :init
  (global-corfu-mode))
#+end_src

** Movement

Enable windmove to use ~SHIFT+arrow~ to move between windows
#+begin_src emacs-lisp
(windmove-default-keybindings)
#+end_src


Switches cursor automatically to new splitted window
#+begin_src emacs-lisp
(defun split-and-follow-horizontally ()
    (interactive)
    (split-window-below)
    (balance-windows)
    (other-window 1))
(global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)

(defun split-and-follow-vertically ()
    (interactive)
    (split-window-right)
    (balance-windows)
    (other-window 1))
(global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+end_src


Move around with avy. Lots of feature, lets start simple with jumping to chars
Would be cool to have a
#+begin_src emacs-lisp
(use-package avy
      :bind
    (("C-z" . avy-goto-char)))
#+end_src


** Dashboard
#+begin_src emacs-lisp
(use-package dashboard
  ;; only show dasboard if opening emacs without file
  :if (< (length command-line-args) 2)
  :diminish dashboard-mode
  :config
  (setq dashboard-banner-logo-title "YOUR ADD HERE")
  (setq dashboard-set-footer nil)
  (setq dashboard-startup-banner "~/.config/emacs/dashboard-logos/orb.png")
  ;; (setq dashboard-startup-banner "~/.config/emacs/dashboard-logos/rms-pepper.png")  
  (setq dashboard-items '((bookmarks . 10)
                          (agenda . 5)                            
                          ;;(projects . 5)
                          (recents . 0)
                          (registers . 5)))
  (setq dashboard-center-content t)
  (dashboard-setup-startup-hook))
#+end_src

** Teminal

Use Vterm, faster than term
neded to install ~sudo dnf install cmake libtool~
needs some more [[https://github.com/akermu/emacs-libvterm#shell-side-configuration][shell-side configuration]]

#+begin_src emacs-lisp
  (use-package vterm
    ;;:when (bound-and-true-p module-file-suffix)
    :commands vterm-mode
    :init
    ;;(add-hook 'vterm-mode-hook
    ;;          (lambda ()
    ;;            (setq confirm-kill-processes nil
    ;;                  hscroll-margin 0)))
    :bind
    (("C-c t t" . vterm))
    :config
    (setq vterm-kill-buffer-on-exit t
          vterm-shell "/usr/bin/fish"))
#+end_src

** File Management

Using dired for file management, some basic tweaks

#+begin_src emacs-lisp
(use-package dired
  :ensure nil
  :config (setq dired-listing-switches "-agho --group-directories-first"))

(when (eq system-type 'darwin)
  (setq insert-directory-program "/opt/homebrew/bin/gls"))
#+end_src
** LLMs

Be wrong faster

#+begin_src emacs-lisp :tangle no
(use-package gptel 
  :ensure nil
  :config
  ;; Remove default backend
  (setq gptel--known-backends nil))

;; Internal OpenAI proxy, only reachable from VPN
(gptel-make-azure "Azure-1"             ; Name, whatever you'd like
  :protocol "https"                     ; Optional -- https is the default
  :host dnl/llm-azure-proxy-url         ; Don't want to leak the internal url
  :endpoint "/v1/chat/completions"      ; Specify endpoint if needed
  :stream t                             ; Enable streaming responses
  :key "foo"                            ; Replace with your Azure API key
  :models '("o1" "o3"))                 ; Specify the model(s) you want to use
#+end_src
* File Editing
** Tab Widths

Default to an indentation size of 2 spaces since it's the norm for pretty much every language I use.

#+begin_src emacs-lisp

(setq-default tab-width 2)
(setq-default evil-shift-width tab-width)

#+end_src

** Spaces over Tabs

Else e.g. Ansible files fail

#+begin_src emacs-lisp

(setq-default indent-tabs-mode nil)

#+end_src

** Commenting Lines

#+begin_src emacs-lisp

(use-package evil-nerd-commenter
  :bind ("M-/" . evilnc-comment-or-uncomment-lines))

#+end_src

** Brackets
Highlight brackets, Autoclose is highly annoying in org mode
#+BEGIN_SRC emacs-lisp
;; Autoclose brackets
;; (electric-pair-mode 1)

;; Highlight brackets
(setq show-paren-delay 0)
(show-paren-mode 1)
#+END_SRC

** Move current line or region up and down

#+BEGIN_SRC emacs-lisp
(use-package move-text
;; meta shift to not collide with orgmode                 
  :bind(("M-S-<up>" . move-text-up)
        ("M-S-<down>" . move-text-down)))
#+END_SRC

* Org Mode

#+begin_src emacs-lisp
(use-package org
  :bind(("C-c a" . org-agenda)
        ("C-c c" . org-capture))
  :custom
  ;; Visual settings
  (org-ellipsis " ▾")
  ;; Set custom TODO states
  (org-todo-keywords '((sequence "TODO(t)" "NEXT(n)" "BLOCKED(b)" "ONGOING(o)" "|" "DONE(d)" "DELEGATED(g)")))
  ;; Start agenda + calendar on Monday
  (org-agenda-start-on-weekday 1)
  (calendar-week-start-day 1)
  ;; Don't show done items in agenda
  (org-agenda-skip-scheduled-if-done t)
  ;; Add timestamp once task is done
  (org-log-done t)
  ;; Set source for agenda
  ;; Find out why to use this `(,var)` syntax
  (org-agenda-files `(,dnl/org-agenda-path))
  ;; Theme source blocks like in native mode
  (org-src-fontify-natively t)
  (org-src-tab-acts-natively t)
  (org-confirm-babel-evaluate nil)
  (org-edit-src-content-indentation 0)
  :config
  ;; collection of examples: https://www.reddit.com/r/emacs/comments/7zqc7b/share_your_org_capture_templates/
  ;; currently loading org-capture templates from dnl-custom-vars
  ;; create a conditional, if it's defined in custom-vars use this, else fall back to default ones
  ;; (setq org-capture-templates
  ;;       '(
  ;;         ("i" "Inbox" entry (file+headline "~/Sync/org/notes.org" "Inbox")
  ;;          "** %?")
  ;;         ("t" "Todo" entry (file+headline "~/Sync/org/notes.org" "GTD")
  ;;          "** TODO %?")
  ;;         ("r" "Recipe" entry (file "~/Sync/org/rezepte.org")
  ;;          "* %? %^G \n:PROPERTIES:\n:Quelle:\n:Menge:\n:Dauer:\n:Kalorien:\n:END:\n** Zutaten\n** Zubereitung\n"
  ;;          :jump-to-captured t)
  ;;         ("b" "Bookmark (Clipboard)" entry (file+headline "~/Sync/org/bookmarks.org" "Captured")
  ;;          "** %(dnl/org-web-tools-insert-link-for-clipboard-url)\n:PROPERTIES:\n:TIMESTAMP: %t\n:END:%?\n" :empty-lines 1 :prepend t)))
  )

(use-package org-modern
  :hook
  (org-mode . global-org-modern-mode)
  :custom
  (org-modern-star nil))
#+end_src

** Block Templates

These templates enable you to type things like =<el= and then hit =Tab= to expand
the template.  More documentation can be found at the Org Mode [[https://orgmode.org/manual/Easy-templates.html][Easy Templates]]
documentation page.

#+begin_src emacs-lisp
;; This is needed as of Org 9.2
(require 'org-tempo)

(add-to-list 'org-structure-template-alist '("sh" . "src sh"))
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("ts" . "src typescript"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
(add-to-list 'org-structure-template-alist '("yaml" . "src yaml"))
(add-to-list 'org-structure-template-alist '("json" . "src json"))
#+end_src

** Capture Web Brookmarks to orgmode

#+begin_src emacs-lisp
(use-package org-web-tools)

(defun dnl/org-web-tools-insert-link-for-clipboard-url ()
  "Extend =org-web-tools-inster-link-for-url= to take URL from clipboard or kill-ring"
  (interactive)
  (org-web-tools--org-link-for-url (org-web-tools--get-first-url)))
#+end_src

* Git
#+begin_src emacs-lisp
(use-package magit)
#+end_src

#+begin_src emacs-lisp
(use-package diff-hl
  :config
  (global-diff-hl-mode)
  (add-hook 'magit-pre-refresh-hook 'diff-hl-magit-pre-refresh)
  (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh))
#+end_src

* Language Support
** Web
*** HTML
Minimal setup for HTML and mixed modes

#+begin_src emacs-lisp
(use-package web-mode
  :config
  :mode (("\\.html\\'" . web-mode)
         ("\\.xml\\'" . web-mode)
         ("\\.tsx\\'" . web-mode)
         )
  :config
  ;; should this rather live under :custom, see: https://erickgnavar.github.io/emacs-config/#orgdb7ae90
           (setq web-mode-markup-indent-offset dnl/indent-width)
           (setq web-mode-code-indent-offset dnl/indent-width)
           (setq web-mode-css-indent-offset dnl/indent-width)
           (setq web-mode-script-padding dnl/indent-width)
           ;; highlight columns
           ;;(setq web-mode-enable-current-column-highlight t)
           ;;(setq web-mode-enable-current-element-highlight t)
           )
#+end_src

**** TODO move tsx out of here and find a better way to integrate it with ts-mode and eglot

Check [[https://vxlabs.com/2022/06/12/typescript-development-with-emacs-tree-sitter-and-lsp-in-2022/?utm_source=pocket_reader][this post]]

*** Emmet

Use emmet to complete HTML abbreviations via ~C-j~. So ~div~ becomes ~<div></div>~

#+begin_src emacs-lisp
(use-package emmet-mode
  :hook ((web-mode . emmet-mode))
  :init
  ;; toggle autocompletion on inline css
  (add-hook 'web-mode-before-auto-complete-hooks
    '(lambda ()
     (let ((web-mode-cur-language
            (web-mode-language-at-pos)))
               (if (string= web-mode-cur-language "css")
           (setq emmet-use-css-transform t)
           (setq emmet-use-css-transform nil))))))
#+end_src

*** JS/TS

Syntax Highlightning for Javascript + Typescript 

#+begin_src emacs-lisp
(use-package typescript-ts-mode
  :after eglot
  :mode (("\\.ts\\'" . typescript-ts-mode)
         ("\\.tsx\\'" . tsx-ts-mode))
  :config
  (setq typescript-ts-mode-indent-offset 4))
#+end_src

#+begin_src emacs-lisp
(use-package js-ts-mode
  :ensure nil ; derived mode
  :after eglot
  :mode(("\\.js\\'" . js-ts-mode)))
#+end_src

**** TODO add yasnippet with complete function definitions
** Lisp Stuff
#+begin_src emacs-lisp

;;(use-package lispy
;;  :hook ((emacs-lisp-mode . lispy-mode)
;;         (scheme-mode . lispy-mode)))


;; fedora defaults to older guile 2 version, need to explicitly set the used guile version
;; ~sudo dnf install guile30~
(use-package geiser
  :config
  (setq geiser-guile-binary "guile3.0")
  )

(use-package geiser-guile
  :after geiser)
#+end_src

** Markdown
#+begin_src emacs-lisp
(use-package markdown-mode
  :mode ("README\\.md\\'" . gfm-mode)
  :init (setq markdown-command "multimarkdown"))
#+end_src

** LSP + Parser
*** treesitter
use treesitter to handle more complex syntax tress for better highlightning. included since emacs 29+

tree-auto to install treesitter major modes automatically
#+begin_src emacs-lisp
(use-package treesit-auto
  :custom
  (treesit-auto-install 'prompt)
  :config
  (treesit-auto-add-to-auto-mode-alist 'all)
  (global-treesit-auto-mode))
#+end_src

**** TODO use [[https://vxlabs.com/2022/06/12/typescript-development-with-emacs-tree-sitter-and-lsp-in-2022/#ensure-for-tsx-configure-for-tree-sitter-based-indentation][tsi with treesitter]] for ts/json/scss indendation?

*** eglot

try something lighter with eglot

#+begin_src emacs-lisp
(use-package eglot
  :hook ((typescript-ts-mode . eglot-ensure)
         (tsx-ts-mode . eglot-ensure)
         (js-ts-mode . eglot-ensure)))
#+end_src

* RSS
#+begin_src emacs-lisp

(use-package elfeed)


(use-package elfeed-org
  :config
  (elfeed-org)
  (setq rmh-elfeed-org-files (list "~/Sync/org/bookmarks.org")))
#+end_src

* Misc
* Stuff to check
** Config Examples
*** https://github.com/alexpeits/emacs.d/blob/master/configuration.org
*** https://github.com/jamiecollinson/dotfiles/blob/master/config.org/
*** https://gitlab.com/Gamino97/dotfiles/-/blob/master/emacs.org
** Packages
*** https://github.com/casouri/vundo

alternative to undo-tree
*** TODO use [[https://github.com/joaotavora/yasnippet][yasnippets]]

use [[https://github.com/microsoft/vscode/blob/174db5eb992d880adcc42c41d83a0e6cb6b92474/extensions/javascript/snippets/javascript.code-snippets][vscode js snippets]] 

or just use predifined [[https://github.com/AndreaCrotti/yasnippet-snippets][yasnippet]]
