#+TITLE: Emacs Config
#+STARTUP: overview
#+PROPERTY: header-args :tangle init.el
* Preface
This literate config is set to  dump all source block into into ~init.el~

This means changes from here do not get automatically get loaded on rerunning Emacs!

To reload config you can:

1. use ~C-c C-v t~ to update ~init.el~ and restart
2. use ~C-x C-e~ on a lisp expression to run it on the fly
3. use ~C-c r~ to run ~dnl/reload-init-file~ to tangle and reload everything in one go

To exclude an SRC block from tangling use ~#:begin_src emacs-lisp :tangle no~

** Load org config via init.el

Always tangles ~emacs.org~ file on startup. Tangling from ~dnl/reload-init-file~ can be removed if used

#+begin_src emacs-lisp :tangle no
;;
;; barebone init.el, load config in literate orgmode file
;;

;; load emacs config in orgmode file
(require 'org)
(org-babel-load-file "~/.emacs.d/emacs.org")

;; alt/new way of loading
;;(org-babel-load-file
;; (expand-file-name
;;  "emacs.org"
;;  user-emacs-directory))
#+end_src
* Cheatsheet
   Cheatsheet for basic emacs commands and commands of packages
** basic commands
*** navigating text
     | C-a   | Move to beginning of line                          |
     | M-m   | Move to first non-whitespace character on the line |
     | C-e   | Move to end of line                                |
     | C-f   | Move forward one character                         |
     | C-b   | Move backward one character                        |
     | M-f   | Move forward one word (I use this a lot)           |
     | M-b   | Move backward one word (I use this a lot, too)     |
     | C-s   | Regex search for text in current buffer            |
     | C-r   | Same as C-s, but search in reverse                 |
     | M-<   | Move to beginning of buffer                        |
     | M->   | Move to end of buffer                              |
     | M-g g | Go to line                                         |

*** manipulating text

     | C-SPC | select region                         |
     | C-w   | Kill region                           |
     | M-w   | Copy region to kill ring              |
     | C-y   | Yank                                  |
     | M-y   | Cycle through kill ring after yanking |
     | M-d   | Kill word                             |
     | C-k   | Kill line                             |

*** navigate windows,
    | C-x o | Switch cursor to another window                                        |
    | C-x 1 | Delete all other windows, leaving only the current window in the frame |
    | C-x 2 | Split frame above and below                                            |
    | C-x 3 | Split frame side by side                                               |
    | C-x 0 | Delete current window                                                  |

** org mode

    [[http://ehneilsen.net/notebook/orgExamples/org-examples.html][comprehensive overview]]
    [[http://orgmode.org/orgcard.txt][reference card]]
    
    | TAB     | toggle subtree |
    | C-c C-l | enter links    |
    | C-c C-e | export file    |

** magit basics

| C-x g | open magit status                                                        |
| S     | stages all files                                                         |
| c c   | initiates a commit. Write the message and press C-c C-c to create commit |
| P u   | pushes to the upstream branch                                            |

* Custom Variables

Setup misc variables to use later.

TODO: find a way to check on which sysem we are (work vs private). Could use ~system-name~, ~user-login-name~.
Or load them from a custom file, check if they are defined here and use defaults if empty.

#+BEGIN_SRC emacs-lisp
(defvar dnl/emacs-conf-path "~/.config/emacs/")
(defvar dnl/emacs-conf-org-path "~/.config/emacs/emacs.org")
(defvar dnl/emacs-conf-init-path "~/.config/.emacs/init.el")
(defvar dnl/default-font "Iosevka")
(defvar dnl/default-variable-font "Cantarell")
(defvar dnl/default-font-size 130)
(defvar dnl/default-variable-font-size 130)
;;(defvar dnl/org-path '(""))
#+END_SRC

* Package Management
#+BEGIN_SRC emacs-lisp
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
			   ("org" . "https://orgmode.org/elpa/")
			   ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
   (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
     (package-install 'use-package))

  (require 'use-package)
  ;; always download packages if they don't already exist
  (setq use-package-always-ensure t)
#+END_SRC

* Keyboard Bindings

General rebindings

#+BEGIN_SRC emacs-lisp
;; Make ESC quit prompts
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

;; Jump to emacs config
(global-set-key (kbd "C-c e") '(lambda ()
			  (interactive)
			  (find-file dnl/emacs-conf-org-path)))

;; Reload Emacs Config
(defun dnl/reload-init-file ()
  (interactive)
  ;; export config to init.el
  (org-babel-tangle-file dnl/emacs-conf-org-path dnl/emacs-conf-init-path)
  ;; reload init file
  (load-file user-init-file)
  ;; restart org mode, else there are some hook issues
  (org-mode-restart))

(global-set-key (kbd "C-c r") 'dnl/reload-init-file) 

;; Show buffer menu
(global-set-key (kbd "C-x C-b") 'buffer-menu)
#+END_SRC

** which-key

Show possible kyebindings after short delay

#+begin_src emacs-lisp
  (use-package which-key
    :init (which-key-mode)
    :diminish which-key-mode
    :config
    (setq which-key-idle-delay 1))
#+end_src

* General Config
** UI
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)

(scroll-bar-mode -1)        ; Disable visible scrollbar
(tool-bar-mode -1)          ; Disable the toolbar
;; (menu-bar-mode -1)          ; Disable the menu bar
(tooltip-mode -1)           ; Disable tooltips
(set-fringe-mode 10)        ; Give some breathing room
(setq ring-bell-function 'ignore) ;; no audio bell

;; show line and column numbers globaly
(column-number-mode)
(global-display-line-numbers-mode t)

;; but don't show line numbers in certain modes
(dolist (mode '(org-mode-hook
	term-mode-hook
	eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))

;; transform yes-or-no questions into y-or-n
(defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

** Theme

#+BEGIN_SRC emacs-lisp
  (use-package spacemacs-theme
    :defer t
    :init
    (load-theme 'spacemacs-light t))
#+END_SRC

#+begin_src emacs-lisp
;;  (use-package doom-themes
;;    :config
;;    (load-theme 'doom-one t))
#+end_src

** Font

#+BEGIN_SRC emacs-lisp
(set-face-attribute 'default nil :font dnl/default-font :height dnl/default-font-size)

;; Set the fixed pitch face
(set-face-attribute 'fixed-pitch nil :font dnl/default-font :height  dnl/default-font-size)

;; Set the variable pitch face
(set-face-attribute 'variable-pitch nil :font dnl/default-variable-font :height dnl/default-font-size :weight 'regular)
#+END_SRC

Use emojis everywhere

   #+begin_src emacs-lisp
(use-package emojify
  :ensure t
  :hook (after-init . global-emojify-mode))
   #+end_src
   
** Modeline

#+BEGIN_SRC emacs-lisp
  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    :custom ((doom-modeline-height 15)))
#+END_SRC

** Saving and Backup

All backup files get sent to /emacs.d/backups to not clutter the file system
   #+BEGIN_SRC emacs-lisp
(setq backup-directory-alist '(("." . "~/.config/emcas/backups/")))
(setq delete-old-versions -1)
(setq version-control t)
(setq vc-make-backup-files t)
(setq auto-save-file-name-transforms '((".*" "~/.config/emacs/auto-save-list/" t)))
   #+END_SRC

** Completion

Use Ivy + Counsel for more convenient completion systems. Basically replace emacs own completion

#+BEGIN_SRC emacs-lisp
      (use-package ivy
	:diminish
	:bind (("C-s" . swiper)
	       :map ivy-minibuffer-map
	       ("TAB" . ivy-alt-done)	
	       ("C-l" . ivy-alt-done)
	       ("C-j" . ivy-next-line)
	       ("C-k" . ivy-previous-line)
	       :map ivy-switch-buffer-map
	       ("C-k" . ivy-previous-line)
	       ("C-l" . ivy-done)
	       ("C-d" . ivy-switch-buffer-kill)
	       :map ivy-reverse-i-search-map
	       ("C-k" . ivy-previous-line)
	       ("C-d" . ivy-reverse-i-search-kill))
	:config
	(ivy-mode 1))

    (use-package counsel
      :bind (
	     ("C-x C-f" . counsel-find-file)
	     ("C-x b" . counsel-ibuffer)
	     ;; ("M-y" . counsel-yank-pop)
	     ("M-x " . counsel-M-x))
      :config
      (counsel-mode 1))
#+END_SRC

* File Editing
** Tab Widths
Default to an indentation size of 2 spaces since it's the norm for pretty much every language I use.

#+begin_src emacs-lisp

  (setq-default tab-width 2)
  (setq-default evil-shift-width tab-width)

#+end_src

** Spaces over Tabs

Else e.g. Ansible files fail

#+begin_src emacs-lisp

  (setq-default indent-tabs-mode nil)

#+end_src

** Commenting Lines

#+begin_src emacs-lisp

  (use-package evil-nerd-commenter
    :bind ("M-/" . evilnc-comment-or-uncomment-lines))

#+end_src

** Brackets
   Highlight brackets, Autoclose is highly annoying in org mode
   #+BEGIN_SRC emacs-lisp
   ;; Autoclose brackets
   ;; (electric-pair-mode 1)

   ;; Highlight brackets
   (setq show-paren-delay 0)
   (show-paren-mode 1)
   #+END_SRC

* Org Mode

Baseline Org Mode config. Add some custom function to run later in 

#+begin_src emacs-lisp
(defun dnl/org-font-setup ()
  ;; Set faces for heading levels, also use the variable font
  (dolist (face '((org-level-1 . 1.2)
                  (org-level-2 . 1.1)
                  (org-level-3 . 1.05)
                  (org-level-4 . 1.0)
                  (org-level-5 . 1.1)
                  (org-level-6 . 1.1)
                  (org-level-7 . 1.1)
                  (org-level-8 . 1.1)))
    (set-face-attribute (car face) nil :font dnl/default-variable-font :weight 'regular :height (cdr face)))

  ;; Ensure that anything that should be fixed-pitch in Org files appears that way
  (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
  (set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-table nil   :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
  (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
  (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch))

(defun dnl/org-mode-setup ()
  (org-indent-mode)
  ;; use variable width font, overwrite some of it via dnl/org-font-setup which is run later
  (variable-pitch-mode 1)
  ;; make sure we have linebreaks in org mode
  (visual-line-mode 1))
#+end_src

Baseline Org Mode config. Also require the package eventhough it should be installed by default.

#+BEGIN_SRC emacs-lisp
(use-package org
  :hook (org-mode . dnl/org-mode-setup)
  :config
  (setq org-ellipsis " ▾")
  ;; shortcut for agenda
  (global-set-key (kbd "C-c a") 'org-agenda)
  ;; don't show done items in agenda
  (setq org-agenda-skip-scheduled-if-done t)

  ;; set source for agenda
  ;;(setq org-agenda-files '("~/Documents/work.org"))
  (setq org-agenda-files '("~/Sync/org/"))

  ;; theme source blocks like in native mode
  (setq org-src-fontify-natively t
      org-src-tab-acts-natively t
      org-confirm-babel-evaluate nil
      org-edit-src-content-indentation 0)

  (dnl/org-font-setup))

;; use custom bullets instead of stars for headings
(use-package org-bullets
:after org
:hook (org-mode . org-bullets-mode)
:custom
(org-bullets-bullet-list '("●" "○" "◉" "○" "●" "○" "●")))


;; use visual-fill-column to center org mode content
(defun dnl/org-mode-visual-fill ()
  (setq visual-fill-column-width 100
        visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(use-package visual-fill-column
  :hook (org-mode . dnl/org-mode-visual-fill))
#+END_SRC

** Block Templates

These templates enable you to type things like =<el= and then hit =Tab= to expand
the template.  More documentation can be found at the Org Mode [[https://orgmode.org/manual/Easy-templates.html][Easy Templates]]
documentation page.

#+begin_src emacs-lisp
;; This is needed as of Org 9.2
(require 'org-tempo)

(add-to-list 'org-structure-template-alist '("sh" . "src sh"))
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("ts" . "src typescript"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
(add-to-list 'org-structure-template-alist '("yaml" . "src yaml"))
(add-to-list 'org-structure-template-alist '("json" . "src json"))
#+end_src

* Git
#+begin_src emacs-lisp
(use-package magit)
#+end_src

#+begin_src emacs-lisp
(use-package diff-hl
  :ensure t
  :config
  (global-diff-hl-mode)
  (add-hook 'magit-pre-refresh-hook 'diff-hl-magit-pre-refresh)
  (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh))
#+end_src

* Config Example
- https://github.com/alexpeits/emacs.d/blob/master/configuration.org
- https://github.com/jamiecollinson/dotfiles/blob/master/config.org/

