(deftheme calcite
  "Distractionless light theme with minimal syntax highlighting")

;; use `M-x list-faces-display` to check which faces to customize
;; mindre-theme for some inspiration https://github.com/erikbackman/mindre-theme/blob/master/mindre-theme.el

(let ((fg "#424242")
      (fg-muted "#9a9a9a")
      (bg "#f1f1f1")
      (blue "#2963b2") ;;old: #008ec4
      (green "#10a778")
      (cyan "#007a7a")
      (yellow "#c8a830")
      (red "#b85450")
      (purple "#523c79")
      (purple-muted "#e8e3f0"))

  ;; Todo: center org tags, fix highlight color in org source blocks same as background
  ;; consult, marginalia and corfu faces
  (custom-theme-set-faces
   'calcite
   `(ansi-color-black ((t (:foreground ,fg :background ,fg))))
   `(ansi-color-blue ((t (:foreground ,blue :background ,blue))))
   `(ansi-color-bold ((t (:weight semi-bold))))
   `(ansi-color-bright-black ((t (:foreground ,fg-muted :background ,fg-muted))))
   `(ansi-color-bright-blue ((t (:foreground ,blue :background ,blue))))
   `(ansi-color-bright-cyan ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-bright-green ((t (:foreground ,green :background ,green))))
   `(ansi-color-bright-magenta ((t (:foreground ,purple :background ,purple))))
   `(ansi-color-bright-red ((t (:foreground ,red :background ,red))))
   `(ansi-color-bright-white ((t (:foreground ,fg :background ,fg))))
   `(ansi-color-bright-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(ansi-color-cyan ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-green ((t (:foreground ,green :background ,green))))
   `(ansi-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(ansi-color-red ((t (:foreground ,red :background ,red))))
   `(ansi-color-white ((t (:foreground ,bg :background ,bg))))
   `(ansi-color-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(bold ((t (:weight semi-bold))))
   `(bold-italic ((t (:weight semi-bold :slant italic))))
   `(buffer-menu-buffer ((t (:weight semi-bold))))
   `(button ((t (:foreground ,fg :underline t))))
   `(compilation-error ((t (:foreground ,red))))
   `(compilation-mode-line-run ((t (:foreground ,fg))))
   `(compilation-warning ((t (:foreground ,yellow))))
   `(completions-annotations ((t (:foreground ,fg-muted))))
   `(completions-common-part ((t (:background ,purple-muted :foreground ,green))))
   `(completions-first-difference ((t (:inherit nil))))
   `(consult-line-number-wrapped ((t (:background ,bg :foreground ,fg))))
   `(corfu-current ((t (:background ,purple-muted :foreground ,fg))))
   `(cursor ((t (:background ,fg :foreground ,bg))))
   `(custom-variable-tag ((t (:foreground ,fg :weight bold))))
   `(default ((t (:background ,bg :foreground ,fg))))
   `(default-italic ((t (:italic t))))
   `(dictionary-reference-face ((t (:foreground ,purple))))
   `(dictionary-word-definition-face ((t (:foreground ,fg))))
   `(diff-added ((t (:background ,purple-muted :foreground ,green))))
   `(diff-changed ((t (:foreground ,fg :weight bold))))
   `(diff-context ((t (:foreground ,fg))))
   `(diff-file-header ((t (:foreground ,fg :weight bold))))
   `(diff-header ((t (:foreground ,fg :weight bold))))
   `(diff-hl-change ((t (:background ,purple :foreground ,purple ))))
   `(diff-hl-delete ((t (:background ,red :foreground ,red))))
   `(diff-hl-insert ((t (:background ,green :foreground, green ))))
   `(diff-refine-added ((t (:foreground ,green :weight bold))))
   `(diff-refine-changed ((t (:weight bold))))
   `(diff-refine-removed ((t (:foreground ,red :strike-through t))))
   `(diff-removed ((t (:background ,purple-muted :foreground ,red))))
   `(dired-broken-symlink ((t (:slant italic :strike-through ,red))))
   `(dired-directory ((t (:weight semi-bold))))
   `(dired-flagged ((t (:foreground ,red))))
   `(dired-header ((t (:foreground ,purple :weight semi-bold))))
   `(dired-marked ((t (:foreground ,purple))))
   `(dired-symlink ((t (:slant italic))))
   `(doom-modeline-buffer-modified ((t (:background ,bg :foreground, purple ))))
   `(eglot-highlight-symbol-face ((t (:underline t))))
   `(eglot-mode-line ((t (:foreground ,fg))))
   `(eglot-mode-line-none-face ((t (:foreground ,fg))))
   `(elfeed-log-date-face ((t (:foreground ,fg-muted))))
   `(elfeed-log-debug-level-face ((t (:foreground ,fg))))
   `(elfeed-log-error-level-face ((t (:weight semi-bold))))
   `(elfeed-log-info-level-face ((t (:foreground ,fg))))
   `(elfeed-log-warn-level-face ((t (:weight semi-bold))))
   `(elfeed-search-date-face ((t (:foreground ,fg))))
   `(elfeed-search-feed-face ((t (:foreground ,purple))))
   `(elfeed-search-filter-face ((t (:foreground ,fg-muted))))
   `(elfeed-search-last-update-face ((t (:foreground ,purple))))
   `(elfeed-search-tag-face ((t (:foreground ,fg))))
   `(elfeed-search-title-face ((t (:foreground ,fg))))
   `(elfeed-search-unread-count-face ((t (:weight semi-bold))))
   `(elfeed-search-unread-title-face ((t (:weight semi-bold))))
   `(error ((t (:foreground ,red))))
   `(flycheck-error ((t (:underline (:style wave :color ,red)))))
   `(flycheck-info ((t (:underline (:style wave :color ,green)))))
   `(flycheck-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flymake-error ((t (:underline (:style wave :color ,red)))))
   `(flymake-note ((t (:underline (:style wave :color ,green)))))
   `(flymake-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flyspell-duplicate ((t (:underline (:style wave :color ,yellow)))))
   `(flyspell-incorrect ((t (:underline (:style wave :color ,red)))))
   `(font-latex-bold-face ((t (:weight semi-bold))))
   `(font-latex-math-face ((t (:foreground ,fg))))
   `(font-latex-script-char-face ((t (:foreground ,fg))))
   `(font-latex-sectioning-2-face ((t (:weight semi-bold :height 1.4))))
   `(font-latex-warning-face ((t (:foreground ,green))))
   `(font-lock-builtin-face ((t (:foreground ,fg))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,blue))))
   `(font-lock-comment-face ((t (:foreground ,blue))))
   `(font-lock-constant-face ((t (:foreground ,fg))))
   `(font-lock-doc-face ((t (:foreground ,fg :weight semi-bold))))
   `(font-lock-function-name-face ((t (:foreground ,fg))))
   `(font-lock-keyword-face ((t (:foreground ,fg))))
   `(font-lock-preprocessor-face ((t (:foreground ,fg))))
   `(font-lock-reference-face ((t (:foreground ,fg))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,fg))))
   `(font-lock-variable-name-face ((t (:foreground ,fg :underline nil))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
   `(fringe ((t (:background ,bg))))
   `(isearch ((t (:background ,purple-muted :foreground ,fg))))
   `(isearch-fail ((t (:foreground ,fg-muted))))                            
   `(isearch-group-1 ((t (:foreground ,bg :background ,purple)))) 
   `(geiser-font-lock-autodoc-current-arg ((t (:foreground ,fg))))
   `(geiser-font-lock-autodoc-identifier ((t (:foreground ,purple))))
   `(header-line ((t (:background ,bg :foreground ,fg))))
   `(help-argument-name ((t (:foreground ,fg))))
   `(help-key-binding ((t (:foreground ,fg :weight bold))))
   `(helpful-heading ((t (:weight semi-bold))))
   `(highlight ((t (:background ,purple-muted))))
   `(hl-line ((t (:background ,purple-muted))))
   `(info-header-node ((t (:foreground ,fg))))
   `(info-index-match ((t (:foreground ,purple))))
   `(info-menu-header ((t (:weight semi-bold))))
   `(info-menu-star ((t (:foreground ,fg))))
   `(info-node ((t (:weight semi-bold))))
   `(info-title-1 ((t (:weight semi-bold))))
   `(info-title-2 ((t (:weight semi-bold))))
   `(info-title-3 ((t (:weight semi-bold))))
   `(info-title-4 ((t (:weight semi-bold))))
   `(italic ((t (:slant italic))))
   `(lazy-highlight ((t (:background ,purple-muted))))
   `(line-number ((t (:background ,bg :foreground ,fg-muted))))
   `(line-number-current-line ((t (:background ,bg :foreground ,purple))))
   `(line-number-major-tick ((t (:foreground ,fg-muted))))
   `(line-number-minor-tick ((t (:foreground ,fg-muted))))
   `(link ((t (:foreground ,fg))))
   `(magit-branch-local ((t (:foreground ,fg))))
   `(magit-branch-remote ((t (:foreground ,fg))))
   `(magit-diff-added ((t (:background ,bg :foreground ,green))))
   `(magit-diff-added-highlight ((t (:background ,bg :foreground ,green))))
   `(magit-diff-context ((t (:background ,bg :foreground ,fg))))
   `(magit-diff-context-highlight ((t (:background ,bg :foreground ,fg))))
   `(magit-diff-file-heading ((t (:foreground ,fg :weight bold))))
   `(magit-diff-hunk-heading ((t (:background ,bg :foreground ,fg))))
   `(magit-diff-hunk-heading-highlight ((t (:background ,purple-muted :foreground ,fg))))
   `(magit-diff-removed ((t (:background ,bg :foreground ,red))))
   `(magit-diff-removed-highlight ((t (:background ,bg :foreground ,red))))
   `(magit-hash ((t (:foreground ,fg))))
   `(magit-section-heading ((t (:foreground ,purple :weight bold))))
   `(magit-section-highlight ((t (:background ,bg))))
   `(magit-tag ((t (:foreground ,fg))))
   `(marginalia-documentation ((t (:inherit completions-annotations :underline nil))))
   `(markdown-blockquote-face ((t (:foreground ,fg))))
   `(markdown-bold-face ((t (:weight semi-bold))))
   `(markdown-code-face ((t (:background ,purple-muted :foreground ,fg))))
   `(markdown-comment-face ((t (:foreground ,fg-muted))))
   `(markdown-header-delimiter-face ((t (:foreground ,fg-muted))))
   `(markdown-header-face ((t (:foreground ,purple :weight semi-bold))))
   `(markdown-header-face-1 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(markdown-header-face-2 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(markdown-header-face-3 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(markdown-header-face-4 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(markdown-header-face-5 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(markdown-header-face-6 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(markdown-inline-code-face ((t (:foreground ,fg :weight semi-bold))))
   `(markdown-italic-face ((t (:slant italic))))
   `(markdown-link-face ((t (:foreground ,purple))))
   `(markdown-list-face ((t (:foreground ,fg))))
   `(markdown-markup-face ((t (:foreground ,fg-muted))))
   `(markdown-pre-face ((t (:background ,purple-muted :foreground ,fg :extend t))))
   `(markdown-reference-face ((t (:foreground ,purple))))
   `(markdown-strike-through-face ((t (:strike-through t))))
   `(markdown-url-face ((t (:foreground ,purple))))
   `(match ((t (:weight bold))))
   `(message-cited-text ((t (:foreground ,fg-muted))))
   `(message-cited-text-1 ((t (:foreground ,fg-muted))))
   `(message-cited-text-2 ((t (:foreground ,fg-muted))))
   `(message-cited-text-3 ((t (:foreground ,fg-muted))))
   `(message-cited-text-4 ((t (:foreground ,fg-muted))))
   `(message-header-cc ((t (:foreground ,fg))))
   `(message-header-name ((t (:weight semi-bold))))
   `(message-header-newsgroups ((t (:foreground ,fg))))
   `(message-header-other ((t (:foreground ,fg))))
   `(message-header-subject ((t (:foreground ,purple))))
   `(message-header-to ((t (:foreground ,purple))))
   `(message-header-xheader ((t (:foreground ,fg))))
   `(message-mml ((t (:weight semi-bold))))
   `(message-separator ((t (:foreground ,fg-muted))))
   `(minibuffer-prompt ((t (:foreground ,fg :weight bold))))
   `(mode-line ((t (:background ,bg :foreground ,fg))))
   `(mode-line-buffer ((t (:foreground ,fg :weight bold))))
   `(mode-line-buffer-id ((t (:weight regular))))
   `(mode-line-emphasis ((t (:weight regular))))
   `(mode-line-inactive ((t (:background ,bg :foreground ,fg))))
   `(mode-line-minor-mode ((t (:weight ultra-light))))
   `(modeline ((t (:background ,bg :foreground ,fg))))
   `(orderless-match-face-0 ((t (:background ,bg :foreground ,purple :weight bold))))
   `(orderless-match-face-1 ((t (:background ,bg :foreground ,green :weight bold))))
   `(orderless-match-face-2 ((t (:background ,bg :foreground ,blue :weight bold))))
   `(orderless-match-face-3 ((t (:background ,bg :foreground ,cyan :weight bold))))
   `(org-agenda-calendar-event ((t (:foreground ,fg))))
   `(org-agenda-calendar-sexp ((t (:foreground ,purple))))
   `(org-agenda-clocking ((t (:foreground ,fg :background ,purple-muted))))
   `(org-agenda-column-dateline ((t (:foreground ,fg-muted))))
   `(org-agenda-current-time ((t (:weight semi-bold))))
   `(org-agenda-date ((t (:foreground ,fg))))
   `(org-agenda-date-today ((t (:foreground ,fg :weight bold))))
   `(org-agenda-date-weekend ((t (:foreground ,fg :weight normal))))
   `(org-agenda-diary ((t (:foreground ,fg-muted))))
   `(org-agenda-dimmed-todo-face ((t (:foreground ,fg-muted))))
   `(org-agenda-done ((t (:foreground ,fg-muted))))
   `(org-agenda-filter-category ((t (:foreground ,fg-muted))))
   `(org-agenda-filter-effort ((t (:foreground ,fg-muted))))
   `(org-agenda-filter-regexp ((t (:foreground ,fg-muted))))
   `(org-agenda-filter-tags ((t (:foreground ,fg-muted))))
   `(org-agenda-property-face ((t (:foreground ,fg-muted))))
   `(org-agenda-restriction-lock ((t (:foreground ,fg-muted))))
   `(org-agenda-structure ((t (:foreground ,fg :weight bold))))
   `(org-archived ((t (:foreground ,fg-muted))))
   `(org-block ((t (:foreground ,fg :background ,purple-muted))))
   `(org-block-begin-line ((t (:foreground ,fg :background ,purple-muted))))
   `(org-block-begin-line ((t (:foreground ,purple-muted))))
   `(org-block-end-line ((t (:foreground ,fg :background ,purple-muted))))
   `(org-block-end-line ((t (:foreground ,purple-muted))))
   `(org-checkbox ((t (:foreground ,fg))))
   `(org-checkbox-statistics-done ((t (:foreground ,fg-muted))))
   `(org-checkbox-statistics-todo ((t (:foreground ,fg))))
   `(org-clock-overlay ((t (:foreground ,fg-muted))))
   `(org-code ((t (:background ,purple-muted :foreground ,fg))))
   `(org-column ((t (:foreground ,fg-muted))))
   `(org-column-title ((t (:foreground ,fg-muted))))
   `(org-date ((t (:foreground ,fg) :underline)))
   `(org-date-selected ((t (:foreground ,bg :background ,purple))))
   `(org-default ((t (:foreground ,fg-muted))))
   `(org-dispatcher-highlight ((t (:foreground ,purple :weight semi-bold))))
   `(org-document-info ((t (:foreground ,fg-muted))))
   `(org-document-info-keyword ((t (:foreground ,fg))))
   `(org-document-title ((t (:foreground ,purple :height 1.0 :underline nil))))
   `(org-done ((t (:foreground ,green))))
   `(org-drawer ((t (:foreground ,fg-muted))))
   `(org-ellipsis ((t (:foreground ,fg))))
   `(org-footnote ((t (:foreground ,fg-muted))))
   `(org-formula ((t (:foreground ,fg-muted))))
   `(org-headline-done ((t (:foreground ,fg-muted))))
   `(org-headline-todo ((t (:foreground ,fg))))
   `(org-hide ((t (:foreground ,bg))))
   `(org-indent ((t (:foreground ,bg))))
   `(org-latex-and-related ((t (:foreground ,fg :background ,bg))))
   `(org-level-1 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(org-level-2 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(org-level-3 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(org-level-4 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(org-level-5 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(org-level-6 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(org-level-7 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(org-level-8 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
   `(org-link ((t (:foreground ,fg :underline t))))
   `(org-list-dt ((t (:foreground ,fg-muted))))
   `(org-macro ((t (:foreground ,fg-muted))))
   `(org-meta-line ((t (:foreground ,fg))))
   `(org-mode-line-clock ((t (:foreground ,fg-muted))))
   `(org-mode-line-clock-overrun ((t (:foreground ,fg-muted))))
   `(org-modern-date-active ((t (:background ,purple-muted))))
   ;;`(org-modern-label ((t ()))))
   `(org-modern-priority ((t (:background ,purple-muted))))
   `(org-modern-statistics ((t (:background ,purple-muted))))
   `(org-priority ((t (:foreground ,fg-muted))))
   `(org-property-value ((t (:foreground ,fg-muted))))
   `(org-quote ((t (:foreground ,fg :slant italic :inherit org-block))))
   `(org-scheduled ((t (:foreground ,fg))))
   `(org-scheduled-previously ((t (:foreground ,fg))))
   `(org-scheduled-today ((t (:foreground ,fg))))
   `(org-sexp-date ((t (:foreground ,fg))))
   `(org-special-keyword ((t (:foreground ,fg))))
   `(org-table ((t (:foreground ,fg))))
   `(org-tag ((t (:weight semi-bold))))
   `(org-tag-group ((t (:foreground ,fg-muted))))
   `(org-target ((t (:foreground ,fg-muted))))
   `(org-time-grid ((t (:foreground ,fg-muted))))
   `(org-todo ((t (:foreground ,purple :background, purple-muted))))
   `(org-upcoming-deadline ((t (:foreground ,fg))))
   `(org-verbatim ((t (:foreground ,fg))))
   `(org-verse ((t (:inherit org-block :slant italic))))
   `(org-warning ((t (:weight semi-bold))))
   `(outline-1 ((t (:weight semi-bold))))
   `(outline-2 ((t (:weight semi-bold))))
   `(outline-3 ((t (:weight semi-bold))))
   `(outline-4 ((t (:weight semi-bold))))
   `(outline-5 ((t (:weight semi-bold))))
   `(outline-6 ((t (:weight semi-bold))))
   `(outline-7 ((t (:weight semi-bold))))
   `(outline-8 ((t (:weight semi-bold))))
   `(package-description ((t (:foreground ,fg))))
   `(package-name ((t (:foreground ,purple))))
   `(package-status-avail-obso ((t (:foreground ,fg-muted))))
   `(package-status-available ((t (:foreground ,fg))))
   `(package-status-built-in ((t (:foreground ,purple))))
   `(package-status-dependency ((t (:foreground ,purple))))
   `(package-status-disabled ((t (:foreground ,fg-muted))))
   `(package-status-installed ((t (:foreground ,purple))))
   `(popup-face ((t (:background ,purple-muted))))
   `(popup-isearch-match ((t (:weight semi-bold))))
   `(popup-menu-face ((t (:background ,purple-muted))))
   `(popup-menu-mouse-face ((t (:background ,fg :foreground ,bg))))
   `(popup-menu-selection-face ((t (:foreground ,purple))))
   `(popup-menu-summary-face ((t (:foreground ,fg-muted))))
   `(popup-scroll-bar-background-face ((t (:background ,purple-muted))))
   `(popup-scroll-bar-foreground-face ((t (:background ,purple-muted))))
   `(popup-summary-face ((t (:foreground ,fg-muted))))
   `(popup-tip-face ((t (:foreground ,bg :background ,fg :weight semi-bold))))
   `(region ((t (:background ,purple-muted :foreground ,fg))))
   `(secondary-selection ((t (:background ,bg :foreground ,green))))
   `(shadow ((t (:foreground ,fg-muted))))
   `(show-paren-match ((t (:background ,purple-muted :foreground ,fg))))
   `(show-paren-mismatch ((t (:background ,red :foreground ,bg))))
   `(success ((t (:foreground ,green))))
   `(term-color-black ((t (:background ,fg :foreground ,fg))))
   `(term-color-blue ((t (:background ,blue :foreground ,blue))))
   `(term-color-cyan ((t (:background ,cyan :foreground ,cyan))))
   `(term-color-green ((t (:background ,green :foreground ,green))))
   `(term-color-magenta ((t (:background ,purple :foreground ,purple))))
   `(term-color-red ((t (:background ,red :foreground ,red))))
   `(term-color-white ((t (:background ,bg :foreground ,bg))))
   `(term-color-yellow ((t (:background ,yellow :foreground ,yellow))))
   `(tooltip ((t (:background ,purple-muted))))
   `(trailing-whitespace ((t (:background ,purple-muted))))
   `(transient-argument ((t (:foreground ,purple :weight bold))))
   `(transient-key ((t (:foreground ,purple :weight bold))))
   `(transient-key-exit ((t (:foreground ,purple :weight bold))))
   `(transient-key-stack ((t (:foreground ,purple :weight bold))))
   `(transient-value ((t (:foreground ,green))))
   `(vertical-border ((t (:foreground ,fg-muted))))
   `(vertico-current ((t (:background ,purple-muted :foreground ,fg))))
   `(vterm-color-black ((t (:background ,fg :foreground ,fg))))
   `(vterm-color-blue ((t (:background ,blue :foreground ,blue))))
   `(vterm-color-bright-black ((t (:background ,fg-muted :foreground ,fg-muted))))
   `(vterm-color-bright-blue ((t (:background ,blue :foreground ,blue))))
   `(vterm-color-bright-cyan ((t (:background ,cyan :foreground ,cyan))))
   `(vterm-color-bright-green ((t (:background ,green :foreground ,green))))
   `(vterm-color-bright-magenta ((t (:background ,purple :foreground ,purple))))
   `(vterm-color-bright-red ((t (:background ,red :foreground ,red))))
   `(vterm-color-bright-white ((t (:background ,fg :foreground ,fg))))
   `(vterm-color-bright-yellow ((t (:background ,yellow :foreground ,yellow))))
   `(vterm-color-cyan ((t (:background ,cyan :foreground ,cyan))))
   `(vterm-color-default ((t (:background ,bg :foreground ,fg))))
   `(vterm-color-green ((t (:background ,green :foreground ,green))))
   `(vterm-color-magenta ((t (:background ,purple :foreground ,purple))))
   `(vterm-color-red ((t (:background ,red :foreground ,red))))
   `(vterm-color-white ((t (:background ,bg :foreground ,bg))))
   `(vterm-color-yellow ((t (:background ,yellow :foreground ,yellow))))
   `(warning ((t (:foreground ,yellow))))
   `(whitespace-empty ((t (:foreground ,yellow))))
   `(whitespace-line ((t (:background ,purple :foreground ,fg))))
   `(whitespace-newline ((t (:foreground ,fg-muted))))
   `(whitespace-space ((t (:foreground ,fg))))
   `(window-divider ((t (:foreground ,bg))))
   `(window-divider-first-pixel ((t (:foreground ,bg))))
   `(window-divider-last-pixel ((t (:foreground ,bg))))
   ))

(provide-theme 'calcite)

;;(provide 'calcite-theme)
