;;; calcite-theme.el --- Shared definitions for calcite themes -*- lexical-binding: t; -*-

;; This file contains the shared color and face definitions used by
;; both calcite-light and calcite-dark themes.

;; Color definitions: each color is a list where:
;; - first element is the light variant; accent variants are lighter
;; - second element is the dark variant; accent variants are darker
(defconst calcite-themes-colors
  '((fg          "#424242" "#f1f1f1")
    (fg-accent   "#9a9a9a" "#6a6a6a")
    (bg          "#f1f1f1" "#2c2b30")
    (blue        "#2963b2" "#2963b2")
    (green       "#10a778" "#10a778")
    (cyan        "#007a7a" "#007a7a")
    (yellow      "#c8a830" "#c8a830")
    (red         "#b85450" "#b85450")
    (purple      "#523c79" "#ebaafa")
    (purple-accent "#e8e3f0" "#4d3e66"))
  "Color palette for calcite themes.
Each color is a list: (light-value dark-value).")

(defun calcite-themes-get-colors (variant)
  "Get color alist for VARIANT (0 for light, 1 for dark)."
  (mapcar (lambda (color-def)
            (cons (car color-def) (nth (1+ variant) color-def)))
          calcite-themes-colors))

(defun calcite-themes-apply (theme-name colors)
  "Apply THEME-NAME with COLORS palette.
COLORS should be an alist with keys: fg, fg-accent, bg, blue, green,
cyan, yellow, red, purple, purple-accent."
  (let ((fg (alist-get 'fg colors))
        (fg-accent (alist-get 'fg-accent colors))
        (bg (alist-get 'bg colors))
        (blue (alist-get 'blue colors))
        (green (alist-get 'green colors))
        (cyan (alist-get 'cyan colors))
        (yellow (alist-get 'yellow colors))
        (red (alist-get 'red colors))
        (purple (alist-get 'purple colors))
        (purple-accent (alist-get 'purple-accent colors)))

    (custom-theme-set-faces
     theme-name
        `(avy-background-face ((t (:foreground ,fg-accent))))
        `(avy-lead-face ((t (:background ,purple :foreground ,bg :weight bold))))
        `(avy-lead-face-0 ((t (:background ,purple-accent :foreground ,purple :weight bold))))
        `(avy-lead-face-1 ((t (:foreground ,purple :weight bold :underline t))))
        `(avy-lead-face-2 ((t (:background ,purple-accent :foreground ,fg :weight bold))))
        `(bold ((t (:weight semi-bold))))
        `(bold-italic ((t (:weight semi-bold :slant italic))))
        `(buffer-menu-buffer ((t (:weight semi-bold))))
        `(button ((t (:foreground ,fg :underline t))))
        `(compilation-error ((t (:foreground ,red))))
        `(compilation-mode-line-run ((t (:foreground ,fg))))
        `(compilation-warning ((t (:foreground ,yellow))))
        `(completions-annotations ((t (:foreground ,fg-accent))))
        `(completions-common-part ((t (:background ,purple-accent :foreground ,green))))
        `(completions-first-difference ((t (:inherit nil))))
        `(consult-async-failed ((t (:foreground ,red :weight bold))))
        `(consult-async-finished ((t (:foreground ,green))))
        `(consult-async-running ((t (:foreground ,yellow))))
        `(consult-bookmark ((t (:foreground ,fg))))
        `(consult-buffer ((t (:foreground ,fg))))
        `(consult-file ((t (:foreground ,fg))))
        `(consult-imenu-prefix ((t (:foreground ,fg-accent))))
        `(consult-key ((t (:foreground ,purple :weight bold))))
        `(consult-line-number ((t (:foreground ,fg-accent))))
        `(consult-line-number-prefix ((t (:foreground ,fg-accent))))
        `(consult-line-number-wrapped ((t (:background ,bg :foreground ,fg))))
        `(consult-narrow-indicator ((t (:foreground ,purple :weight bold))))
        `(consult-preview-cursor ((t (:background ,purple))))
        `(consult-preview-line ((t (:background ,purple-accent))))
        `(corfu-annotations ((t (:foreground ,fg-accent))))
        `(corfu-bar ((t (:background ,fg))))
        `(corfu-border ((t (:background ,fg-accent))))
        `(corfu-current ((t (:background ,purple-accent :foreground ,fg))))
        `(corfu-default ((t (:background ,purple-accent :foreground ,fg))))
        `(corfu-deprecated ((t (:foreground ,fg-accent :strike-through t))))
        `(corfu-echo ((t (:foreground ,fg-accent))))
        `(cursor ((t (:background ,fg :foreground ,bg))))
        `(custom-variable-tag ((t (:foreground ,fg :weight bold))))
        `(default ((t (:background ,bg :foreground ,fg))))
        `(default-italic ((t (:italic t))))
        `(dictionary-reference-face ((t (:foreground ,purple))))
        `(dictionary-word-definition-face ((t (:foreground ,fg))))
        `(diff-added ((t (:background ,purple-accent :foreground ,green))))
        `(diff-changed ((t (:foreground ,fg :weight bold))))
        `(diff-context ((t (:foreground ,fg))))
        `(diff-file-header ((t (:foreground ,fg :weight bold))))
        `(diff-header ((t (:foreground ,fg :weight bold))))
        `(diff-hl-change ((t (:background ,purple :foreground ,purple ))))
        `(diff-hl-delete ((t (:background ,red :foreground ,red))))
        `(diff-hl-insert ((t (:background ,green :foreground ,green))))
        `(diff-refine-added ((t (:foreground ,green :weight bold))))
        `(diff-refine-changed ((t (:weight bold))))
        `(diff-refine-removed ((t (:foreground ,red :strike-through t))))
        `(diff-removed ((t (:background ,purple-accent :foreground ,red))))
        `(dired-broken-symlink ((t (:slant italic :strike-through ,red))))
        `(dired-directory ((t (:weight semi-bold))))
        `(dired-flagged ((t (:foreground ,red))))
        `(dired-header ((t (:foreground ,purple :weight semi-bold))))
        `(dired-marked ((t (:foreground ,purple))))
        `(dired-symlink ((t (:slant italic))))
        `(doom-modeline-bar ((t (:background ,purple))))
        `(doom-modeline-bar-inactive ((t (:background ,fg-accent))))
        `(doom-modeline-buffer-file ((t (:foreground ,fg :weight semi-bold))))
        `(doom-modeline-buffer-major-mode ((t (:foreground ,fg))))
        `(doom-modeline-buffer-minor-mode ((t (:foreground ,fg-accent))))
        `(doom-modeline-buffer-modified ((t (:foreground ,purple :weight bold))))
        `(doom-modeline-buffer-path ((t (:foreground ,fg))))
        `(doom-modeline-debug ((t (:foreground ,yellow))))
        `(doom-modeline-info ((t (:foreground ,purple))))
        `(doom-modeline-lsp-error ((t (:foreground ,red))))
        `(doom-modeline-lsp-success ((t (:foreground ,green))))
        `(doom-modeline-lsp-warning ((t (:foreground ,yellow))))
        `(doom-modeline-panel ((t (:background ,bg :foreground ,fg))))
        `(doom-modeline-project-dir ((t (:foreground ,fg :weight semi-bold))))
        `(doom-modeline-project-parent-dir ((t (:foreground ,fg))))
        `(doom-modeline-project-root-dir ((t (:foreground ,purple :weight semi-bold))))
        `(doom-modeline-urgent ((t (:foreground ,red :weight bold))))
        `(doom-modeline-vcs-default ((t (:foreground ,purple :weight semi-bold))))
        `(doom-modeline-warning ((t (:foreground ,yellow))))
        `(eglot-highlight-symbol-face ((t (:underline t))))
        `(eglot-mode-line ((t (:foreground ,fg))))
        `(eglot-mode-line-none-face ((t (:foreground ,fg))))
        `(elfeed-log-date-face ((t (:foreground ,fg-accent))))
        `(elfeed-log-debug-level-face ((t (:foreground ,fg))))
        `(elfeed-log-error-level-face ((t (:weight semi-bold))))
        `(elfeed-log-info-level-face ((t (:foreground ,fg))))
        `(elfeed-log-warn-level-face ((t (:weight semi-bold))))
        `(elfeed-search-date-face ((t (:foreground ,fg))))
        `(elfeed-search-feed-face ((t (:foreground ,purple))))
        `(elfeed-search-filter-face ((t (:foreground ,fg-accent))))
        `(elfeed-search-last-update-face ((t (:foreground ,purple))))
        `(elfeed-search-tag-face ((t (:foreground ,fg))))
        `(elfeed-search-title-face ((t (:foreground ,fg))))
        `(elfeed-search-unread-count-face ((t (:weight semi-bold))))
        `(elfeed-search-unread-title-face ((t (:weight semi-bold))))
        `(error ((t (:foreground ,red))))
        `(flycheck-error ((t (:underline (:style wave :color ,red)))))
        `(flycheck-info ((t (:underline (:style wave :color ,green)))))
        `(flycheck-warning ((t (:underline (:style wave :color ,yellow)))))
        `(flymake-error ((t (:underline (:style wave :color ,red)))))
        `(flymake-note ((t (:underline (:style wave :color ,green)))))
        `(flymake-warning ((t (:underline (:style wave :color ,yellow)))))
        `(flyspell-duplicate ((t (:underline (:style wave :color ,yellow)))))
        `(flyspell-incorrect ((t (:underline (:style wave :color ,red)))))
        `(font-latex-bold-face ((t (:weight semi-bold))))
        `(font-latex-math-face ((t (:foreground ,fg))))
        `(font-latex-script-char-face ((t (:foreground ,fg))))
        `(font-latex-sectioning-2-face ((t (:weight semi-bold :height 1.4))))
        `(font-latex-warning-face ((t (:foreground ,green))))
        `(font-lock-builtin-face ((t (:foreground ,fg))))
        `(font-lock-comment-delimiter-face ((t (:foreground ,fg-accent))))
        `(font-lock-comment-face ((t (:foreground ,fg-accent :background unspecified))))
        `(font-lock-constant-face ((t (:foreground ,fg))))
        `(font-lock-doc-face ((t (:foreground ,fg :weight semi-bold))))
        `(font-lock-function-name-face ((t (:foreground ,fg))))
        `(font-lock-keyword-face ((t (:foreground ,fg))))
        `(font-lock-preprocessor-face ((t (:foreground ,fg))))
        `(font-lock-reference-face ((t (:foreground ,fg))))
        `(font-lock-string-face ((t (:foreground ,purple))))
        `(font-lock-type-face ((t (:foreground ,fg))))
        `(font-lock-variable-name-face ((t (:foreground ,fg :underline nil))))
        `(font-lock-warning-face ((t (:foreground ,red :weight bold))))
        `(fringe ((t (:background ,bg))))
        `(isearch ((t (:background ,purple-accent :foreground ,fg))))
        `(isearch-fail ((t (:foreground ,fg-accent))))                            
        `(isearch-group-1 ((t (:foreground ,bg :background ,purple)))) 
        `(geiser-font-lock-autodoc-current-arg ((t (:foreground ,fg))))
        `(geiser-font-lock-autodoc-identifier ((t (:foreground ,purple))))
        `(header-line ((t (:background ,bg :foreground ,fg))))
        `(help-argument-name ((t (:foreground ,fg))))
        `(help-key-binding ((t (:foreground ,fg :weight bold))))
        `(helpful-heading ((t (:weight semi-bold))))
        `(highlight ((t (:background ,purple-accent))))
        `(hl-line ((t (:background ,purple-accent))))
        `(info-header-node ((t (:foreground ,fg))))
        `(info-index-match ((t (:foreground ,purple))))
        `(info-menu-header ((t (:weight semi-bold))))
        `(info-menu-star ((t (:foreground ,fg))))
        `(info-node ((t (:weight semi-bold))))
        `(info-title-1 ((t (:weight semi-bold))))
        `(info-title-2 ((t (:weight semi-bold))))
        `(info-title-3 ((t (:weight semi-bold))))
        `(info-title-4 ((t (:weight semi-bold))))
        `(italic ((t (:slant italic))))
        `(lazy-highlight ((t (:background ,purple-accent))))
        `(line-number ((t (:background ,bg :foreground ,fg-accent))))
        `(line-number-current-line ((t (:background ,bg :foreground ,purple))))
        `(line-number-major-tick ((t (:foreground ,fg-accent))))
        `(line-number-minor-tick ((t (:foreground ,fg-accent))))
        `(link ((t (:foreground ,fg))))
        `(magit-branch-local ((t (:foreground ,fg))))
        `(magit-branch-remote ((t (:foreground ,fg))))
        `(magit-diff-added ((t (:background ,bg :foreground ,green))))
        `(magit-diff-added-highlight ((t (:background ,bg :foreground ,green))))
        `(magit-diff-context ((t (:background ,bg :foreground ,fg))))
        `(magit-diff-context-highlight ((t (:background ,bg :foreground ,fg))))
        `(magit-diff-file-heading ((t (:foreground ,fg :weight bold))))
        `(magit-diff-hunk-heading ((t (:background ,bg :foreground ,fg))))
        `(magit-diff-hunk-heading-highlight ((t (:background ,purple-accent :foreground ,fg))))
        `(magit-diff-removed ((t (:background ,bg :foreground ,red))))
        `(magit-diff-removed-highlight ((t (:background ,bg :foreground ,red))))
        `(magit-hash ((t (:foreground ,fg))))
        `(magit-section-heading ((t (:foreground ,purple :weight bold))))
        `(magit-section-highlight ((t (:background ,bg))))
        `(magit-tag ((t (:foreground ,fg))))
        `(marginalia-archive ((t (:foreground ,fg))))
        `(marginalia-char ((t (:foreground ,fg))))
        `(marginalia-date ((t (:foreground ,fg-accent))))
        `(marginalia-documentation ((t (:inherit completions-annotations :underline nil))))
        `(marginalia-file-modes ((t (:foreground ,fg-accent))))
        `(marginalia-file-name ((t (:foreground ,fg))))
        `(marginalia-file-owner ((t (:foreground ,fg-accent))))
        `(marginalia-function ((t (:foreground ,fg))))
        `(marginalia-installed ((t (:foreground ,green))))
        `(marginalia-key ((t (:foreground ,purple))))
        `(marginalia-list ((t (:foreground ,fg))))
        `(marginalia-mode ((t (:foreground ,fg))))
        `(marginalia-null ((t (:foreground ,fg-accent))))
        `(marginalia-number ((t (:foreground ,fg))))
        `(marginalia-off ((t (:foreground ,fg-accent))))
        `(marginalia-on ((t (:foreground ,green))))
        `(marginalia-size ((t (:foreground ,fg-accent))))
        `(marginalia-string ((t (:foreground ,green))))
        `(marginalia-symbol ((t (:foreground ,fg))))
        `(marginalia-true ((t (:foreground ,green))))
        `(marginalia-type ((t (:foreground ,fg))))
        `(marginalia-value ((t (:foreground ,fg))))
        `(marginalia-version ((t (:foreground ,fg-accent))))
        `(markdown-blockquote-face ((t (:foreground ,fg))))
        `(markdown-bold-face ((t (:weight semi-bold))))
        `(markdown-code-face ((t (:background ,purple-accent :foreground ,fg))))
        `(markdown-comment-face ((t (:foreground ,fg-accent))))
        `(markdown-header-delimiter-face ((t (:foreground ,fg-accent))))
        `(markdown-header-face ((t (:foreground ,purple :weight semi-bold))))
        `(markdown-header-face-1 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(markdown-header-face-2 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(markdown-header-face-3 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(markdown-header-face-4 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(markdown-header-face-5 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(markdown-header-face-6 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(markdown-inline-code-face ((t (:foreground ,fg :weight semi-bold))))
        `(markdown-italic-face ((t (:slant italic))))
        `(markdown-link-face ((t (:foreground ,purple))))
        `(markdown-list-face ((t (:foreground ,fg))))
        `(markdown-markup-face ((t (:foreground ,fg-accent))))
        `(markdown-pre-face ((t (:background ,purple-accent :foreground ,fg :extend t))))
        `(markdown-reference-face ((t (:foreground ,purple))))
        `(markdown-strike-through-face ((t (:strike-through t))))
        `(markdown-url-face ((t (:foreground ,purple))))
        `(match ((t (:weight bold))))
        `(message-cited-text ((t (:foreground ,fg-accent))))
        `(message-cited-text-1 ((t (:foreground ,fg-accent))))
        `(message-cited-text-2 ((t (:foreground ,fg-accent))))
        `(message-cited-text-3 ((t (:foreground ,fg-accent))))
        `(message-cited-text-4 ((t (:foreground ,fg-accent))))
        `(message-header-cc ((t (:foreground ,fg))))
        `(message-header-name ((t (:weight semi-bold))))
        `(message-header-newsgroups ((t (:foreground ,fg))))
        `(message-header-other ((t (:foreground ,fg))))
        `(message-header-subject ((t (:foreground ,purple))))
        `(message-header-to ((t (:foreground ,purple))))
        `(message-header-xheader ((t (:foreground ,fg))))
        `(message-mml ((t (:weight semi-bold))))
        `(message-separator ((t (:foreground ,fg-accent))))
        `(minibuffer-prompt ((t (:foreground ,fg :weight bold))))
        `(mode-line ((t (:background ,bg :foreground ,fg))))
        `(mode-line-buffer ((t (:foreground ,fg :weight bold))))
        `(mode-line-buffer-id ((t (:weight regular))))
        `(mode-line-emphasis ((t (:weight regular))))
        `(mode-line-inactive ((t (:background ,bg :foreground ,fg))))
        `(mode-line-minor-mode ((t (:weight ultra-light))))
        `(modeline ((t (:background ,bg :foreground ,fg))))
        `(orderless-match-face-0 ((t (:background ,bg :foreground ,purple :weight bold))))
        `(orderless-match-face-1 ((t (:background ,bg :foreground ,green :weight bold))))
        `(orderless-match-face-2 ((t (:background ,bg :foreground ,blue :weight bold))))
        `(orderless-match-face-3 ((t (:background ,bg :foreground ,cyan :weight bold))))
        `(org-agenda-calendar-event ((t (:foreground ,fg))))
        `(org-agenda-calendar-sexp ((t (:foreground ,purple))))
        `(org-agenda-clocking ((t (:foreground ,fg :background ,purple-accent))))
        `(org-agenda-column-dateline ((t (:foreground ,fg-accent))))
        `(org-agenda-current-time ((t (:weight semi-bold))))
        `(org-agenda-date ((t (:foreground ,fg))))
        `(org-agenda-date-today ((t (:foreground ,fg :weight bold))))
        `(org-agenda-date-weekend ((t (:foreground ,fg :weight normal))))
        `(org-agenda-diary ((t (:foreground ,fg-accent))))
        `(org-agenda-dimmed-todo-face ((t (:foreground ,fg-accent))))
        `(org-agenda-done ((t (:foreground ,fg-accent))))
        `(org-agenda-filter-category ((t (:foreground ,fg-accent))))
        `(org-agenda-filter-effort ((t (:foreground ,fg-accent))))
        `(org-agenda-filter-regexp ((t (:foreground ,fg-accent))))
        `(org-agenda-filter-tags ((t (:foreground ,fg-accent))))
        `(org-agenda-property-face ((t (:foreground ,fg-accent))))
        `(org-agenda-restriction-lock ((t (:foreground ,fg-accent))))
        `(org-agenda-structure ((t (:foreground ,fg :weight bold))))
        `(org-archived ((t (:foreground ,fg-accent))))
        `(org-block ((t (:foreground ,fg :background ,purple-accent))))
        `(org-block-begin-line ((t (:foreground ,fg :background ,purple-accent))))
        `(org-block-end-line ((t (:foreground ,fg :background ,purple-accent))))
        `(org-checkbox ((t (:foreground ,fg))))
        `(org-checkbox-statistics-done ((t (:foreground ,fg-accent))))
        `(org-checkbox-statistics-todo ((t (:foreground ,fg))))
        `(org-clock-overlay ((t (:foreground ,fg-accent))))
        `(org-code ((t (:background ,purple-accent :foreground ,fg))))
        `(org-column ((t (:foreground ,fg-accent))))
        `(org-column-title ((t (:foreground ,fg-accent))))
        `(org-date ((t (:foreground ,fg :underline t))))
        `(org-date-selected ((t (:foreground ,bg :background ,purple))))
        `(org-default ((t (:foreground ,fg-accent))))
        `(org-dispatcher-highlight ((t (:foreground ,purple :weight semi-bold))))
        `(org-document-info ((t (:foreground ,fg-accent))))
        `(org-document-info-keyword ((t (:foreground ,fg))))
        `(org-document-title ((t (:foreground ,purple :height 1.0 :underline nil))))
        `(org-done ((t (:foreground ,green))))
        `(org-drawer ((t (:foreground ,fg-accent))))
        `(org-ellipsis ((t (:foreground ,fg))))
        `(org-footnote ((t (:foreground ,fg-accent))))
        `(org-formula ((t (:foreground ,fg-accent))))
        `(org-headline-done ((t (:foreground ,fg-accent))))
        `(org-headline-todo ((t (:foreground ,fg))))
        `(org-hide ((t (:foreground ,bg))))
        `(org-indent ((t (:foreground ,bg))))
        `(org-latex-and-related ((t (:foreground ,fg :background ,bg))))
        `(org-level-1 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(org-level-2 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(org-level-3 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(org-level-4 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(org-level-5 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(org-level-6 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(org-level-7 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(org-level-8 ((t (:foreground ,purple :weight semi-bold :height 1.1))))
        `(org-link ((t (:foreground ,fg :underline t))))
        `(org-list-dt ((t (:foreground ,fg-accent))))
        `(org-macro ((t (:foreground ,fg-accent))))
        `(org-meta-line ((t (:foreground ,fg))))
        `(org-mode-line-clock ((t (:foreground ,fg-accent))))
        `(org-mode-line-clock-overrun ((t (:foreground ,fg-accent))))
        `(org-modern-date-active ((t (:background ,purple-accent))))
        `(org-modern-label ((t (:inherit nil)))) ;; else corfu complains
        `(org-modern-priority ((t (:background ,purple-accent))))
        `(org-modern-statistics ((t (:background ,purple-accent))))
        `(org-priority ((t (:foreground ,fg-accent))))
        `(org-property-value ((t (:foreground ,fg-accent))))
        `(org-quote ((t (:foreground ,fg :slant italic :inherit org-block))))
        `(org-scheduled ((t (:foreground ,fg))))
        `(org-scheduled-previously ((t (:foreground ,fg))))
        `(org-scheduled-today ((t (:foreground ,fg))))
        `(org-sexp-date ((t (:foreground ,fg))))
        `(org-special-keyword ((t (:foreground ,fg))))
        `(org-table ((t (:foreground ,fg))))
        `(org-tag ((t (:weight semi-bold))))
        `(org-tag-group ((t (:foreground ,fg-accent))))
        `(org-target ((t (:foreground ,fg-accent))))
        `(org-time-grid ((t (:foreground ,fg-accent))))
        `(org-todo ((t (:foreground ,purple :background ,purple-accent))))
        `(org-upcoming-deadline ((t (:foreground ,fg))))
        `(org-verbatim ((t (:foreground ,fg))))
        `(org-verse ((t (:inherit org-block :slant italic))))
        `(org-warning ((t (:weight semi-bold))))
        `(outline-1 ((t (:weight semi-bold))))
        `(outline-2 ((t (:weight semi-bold))))
        `(outline-3 ((t (:weight semi-bold))))
        `(outline-4 ((t (:weight semi-bold))))
        `(outline-5 ((t (:weight semi-bold))))
        `(outline-6 ((t (:weight semi-bold))))
        `(outline-7 ((t (:weight semi-bold))))
        `(outline-8 ((t (:weight semi-bold))))
        `(package-description ((t (:foreground ,fg))))
        `(package-name ((t (:foreground ,purple))))
        `(package-status-avail-obso ((t (:foreground ,fg-accent))))
        `(package-status-available ((t (:foreground ,fg))))
        `(package-status-built-in ((t (:foreground ,purple))))
        `(package-status-dependency ((t (:foreground ,purple))))
        `(package-status-disabled ((t (:foreground ,fg-accent))))
        `(package-status-installed ((t (:foreground ,purple))))
        `(region ((t (:background ,purple-accent :foreground ,fg))))
        `(secondary-selection ((t (:background ,bg :foreground ,green))))
        `(shadow ((t (:foreground ,fg-accent))))
        `(show-paren-match ((t (:background ,purple-accent :foreground ,fg))))
        `(show-paren-mismatch ((t (:background ,red :foreground ,bg))))
        `(success ((t (:foreground ,green))))
        `(term-color-black ((t (:background ,fg :foreground ,fg))))
        `(term-color-blue ((t (:background ,blue :foreground ,blue))))
        `(term-color-cyan ((t (:background ,cyan :foreground ,cyan))))
        `(term-color-green ((t (:background ,green :foreground ,green))))
        `(term-color-magenta ((t (:background ,purple :foreground ,purple))))
        `(term-color-red ((t (:background ,red :foreground ,red))))
        `(term-color-white ((t (:background ,bg :foreground ,bg))))
        `(term-color-yellow ((t (:background ,yellow :foreground ,yellow))))
        `(tooltip ((t (:background ,purple-accent))))
        `(trailing-whitespace ((t (:background ,purple-accent))))
        `(transient-argument ((t (:foreground ,purple :weight bold))))
        `(transient-key ((t (:foreground ,purple :weight bold))))
        `(transient-key-exit ((t (:foreground ,purple :weight bold))))
        `(transient-key-stack ((t (:foreground ,purple :weight bold))))
        `(transient-value ((t (:foreground ,green))))
        `(vertical-border ((t (:foreground ,fg-accent))))
        `(vertico-current ((t (:background ,purple-accent :foreground ,fg))))
        `(vterm-color-black ((t (:background ,fg :foreground ,fg))))
        `(vterm-color-blue ((t (:background ,blue :foreground ,blue))))
        `(vterm-color-bright-black ((t (:background ,fg-accent :foreground ,fg-accent))))
        `(vterm-color-bright-blue ((t (:background ,blue :foreground ,blue))))
        `(vterm-color-bright-cyan ((t (:background ,cyan :foreground ,cyan))))
        `(vterm-color-bright-green ((t (:background ,green :foreground ,green))))
        `(vterm-color-bright-magenta ((t (:background ,purple :foreground ,purple))))
        `(vterm-color-bright-red ((t (:background ,red :foreground ,red))))
        `(vterm-color-bright-white ((t (:background ,fg :foreground ,fg))))
        `(vterm-color-bright-yellow ((t (:background ,yellow :foreground ,yellow))))
        `(vterm-color-cyan ((t (:background ,cyan :foreground ,cyan))))
        `(vterm-color-default ((t (:background ,bg :foreground ,fg))))
        `(vterm-color-green ((t (:background ,green :foreground ,green))))
        `(vterm-color-magenta ((t (:background ,purple :foreground ,purple))))
        `(vterm-color-red ((t (:background ,red :foreground ,red))))
        `(vterm-color-white ((t (:background ,bg :foreground ,bg))))
        `(vterm-color-yellow ((t (:background ,yellow :foreground ,yellow))))
        `(warning ((t (:foreground ,yellow))))
        `(whitespace-empty ((t (:foreground ,yellow))))
        `(whitespace-line ((t (:background ,purple :foreground ,fg))))
        `(whitespace-newline ((t (:foreground ,fg-accent))))
        `(whitespace-space ((t (:foreground ,fg))))
        `(window-divider ((t (:foreground ,bg))))
        `(window-divider-first-pixel ((t (:foreground ,bg))))
        `(window-divider-last-pixel ((t (:foreground ,bg))))
        )))

(provide 'calcite-theme)
;;; calcite-theme.el ends here
